/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:0fd6fea5-75f0-4ab7-bef9-9ee5a2e66343",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_HJ3wRUD8z",
    "aws_user_pools_web_client_id": "gojgf68pe71826mbl3ebehj17",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://kls2zkllrzanfpytsomar3qyku.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yov4pkutb5guhcufrbse3qs4pm",
    "aws_cloud_logic_custom": [
        {
            "name": "helloApi",
            "endpoint": "https://99dak72sa0.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ],
    "aws_mobile_analytics_app_id": "ea8c334e627e4420a09b3a59af07695d",
    "aws_mobile_analytics_app_region": "us-west-2",
    "aws_user_files_s3_bucket": "nextjsv12dsfilestorage101933-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
